server:
  port: 8080
spring:
  #定义多数据源
  datasource-test1:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 147258asd
    hikari:
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired）
      #      max-lifetime: 60000
      #连接池中允许的最大连接数
      maximum-pool-size: 15
      #<!-- 生效超时 -->
      validation-timeout: 3000
      #连接只读数据库时配置为true， 保证安全
      read-only: false
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException
      connection-timeout: 60000
      #一个连接idle状态的最大时长（毫秒），超时则被释放（retired）
      idle-timeout: 60000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQLwait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 120000
  datasource-test2:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 147258asd
    hikari:
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired）
      #      max-lifetime: 60000
      #连接池中允许的最大连接数
      maximum-pool-size: 15
      #<!-- 生效超时 -->
      validation-timeout: 3000
      #连接只读数据库时配置为true， 保证安全
      read-only: false
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException
      connection-timeout: 60000
      #一个连接idle状态的最大时长（毫秒），超时则被释放（retired）
      idle-timeout: 60000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQLwait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 120000
#logging:
#  level:
#    root: debug